application: dhwvustfeffupr
version: 1
runtime: python
api_version: 1

handlers:
- url: /mail.py
  script: mail.py
  
- url: /main.py
  script: main.py

- url: /crawl.py
  script: crawl.py
  
- url: /live.py
  script: live.py

- url: /store.py
  script: store.py
  
- url: /fetch.py
  script: fetch.py

- url: /admin.py
  script: admin.py


- url: /model.py
  script: model.py

- url: /static
  static_dir: static
  
- url: /picture/.*
  script: picture.py
  
- url: /click/.*
  script: clickbank.py

- url: /msn.py
  script: msn.py

- url: /.*
  script: redirect.py

