<?php
$data = array (
  436 => 
  array (
    'cat_id' => '436',
    'cat_name' => 'Cell Phones',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '436',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '436',
    'name' => 'Cell Phones',
  ),
  439 => 
  array (
    'cat_id' => '439',
    'cat_name' => 'Nokia',
    'measure_unit' => '',
    'parent_id' => '436',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '439',
    'has_children' => '0',
    'goods_num' => '18',
    'level' => 1,
    'id' => '439',
    'name' => 'Nokia',
  ),
  440 => 
  array (
    'cat_id' => '440',
    'cat_name' => 'HTC',
    'measure_unit' => '',
    'parent_id' => '436',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '440',
    'has_children' => '0',
    'goods_num' => '13',
    'level' => 1,
    'id' => '440',
    'name' => 'HTC',
  ),
  441 => 
  array (
    'cat_id' => '441',
    'cat_name' => 'Sumsung',
    'measure_unit' => '',
    'parent_id' => '436',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '441',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '441',
    'name' => 'Sumsung',
  ),
  442 => 
  array (
    'cat_id' => '442',
    'cat_name' => 'LG',
    'measure_unit' => '',
    'parent_id' => '436',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '442',
    'has_children' => '0',
    'goods_num' => '5',
    'level' => 1,
    'id' => '442',
    'name' => 'LG',
  ),
  452 => 
  array (
    'cat_id' => '452',
    'cat_name' => 'BlackBerry',
    'measure_unit' => '',
    'parent_id' => '436',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '452',
    'has_children' => '0',
    'goods_num' => '7',
    'level' => 1,
    'id' => '452',
    'name' => 'BlackBerry',
  ),
  453 => 
  array (
    'cat_id' => '453',
    'cat_name' => 'Sony Ericsson',
    'measure_unit' => '',
    'parent_id' => '436',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '453',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '453',
    'name' => 'Sony Ericsson',
  ),
  504 => 
  array (
    'cat_id' => '504',
    'cat_name' => 'Apple',
    'measure_unit' => '',
    'parent_id' => '436',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '504',
    'has_children' => '0',
    'goods_num' => '8',
    'level' => 1,
    'id' => '504',
    'name' => 'Apple',
  ),
  534 => 
  array (
    'cat_id' => '534',
    'cat_name' => 'Motorola',
    'measure_unit' => '',
    'parent_id' => '436',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '534',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '534',
    'name' => 'Motorola',
  ),
  437 => 
  array (
    'cat_id' => '437',
    'cat_name' => 'Laptop Computers',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '437',
    'has_children' => '10',
    'goods_num' => 0,
    'level' => 0,
    'id' => '437',
    'name' => 'Laptop Computers',
  ),
  443 => 
  array (
    'cat_id' => '443',
    'cat_name' => 'Acer',
    'measure_unit' => '',
    'parent_id' => '437',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '443',
    'has_children' => '0',
    'goods_num' => '13',
    'level' => 1,
    'id' => '443',
    'name' => 'Acer',
  ),
  444 => 
  array (
    'cat_id' => '444',
    'cat_name' => 'Sony',
    'measure_unit' => '',
    'parent_id' => '437',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '444',
    'has_children' => '0',
    'goods_num' => '58',
    'level' => 1,
    'id' => '444',
    'name' => 'Sony',
  ),
  445 => 
  array (
    'cat_id' => '445',
    'cat_name' => 'Asus',
    'measure_unit' => '',
    'parent_id' => '437',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '445',
    'has_children' => '0',
    'goods_num' => '30',
    'level' => 1,
    'id' => '445',
    'name' => 'Asus',
  ),
  449 => 
  array (
    'cat_id' => '449',
    'cat_name' => 'HP',
    'measure_unit' => '',
    'parent_id' => '437',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '449',
    'has_children' => '0',
    'goods_num' => '31',
    'level' => 1,
    'id' => '449',
    'name' => 'HP',
  ),
  450 => 
  array (
    'cat_id' => '450',
    'cat_name' => 'Apple',
    'measure_unit' => '',
    'parent_id' => '437',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '450',
    'has_children' => '0',
    'goods_num' => '27',
    'level' => 1,
    'id' => '450',
    'name' => 'Apple',
  ),
  451 => 
  array (
    'cat_id' => '451',
    'cat_name' => 'Toshiba',
    'measure_unit' => '',
    'parent_id' => '437',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '451',
    'has_children' => '0',
    'goods_num' => '27',
    'level' => 1,
    'id' => '451',
    'name' => 'Toshiba',
  ),
  516 => 
  array (
    'cat_id' => '516',
    'cat_name' => 'Dell',
    'measure_unit' => '',
    'parent_id' => '437',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '516',
    'has_children' => '0',
    'goods_num' => '16',
    'level' => 1,
    'id' => '516',
    'name' => 'Dell',
  ),
  540 => 
  array (
    'cat_id' => '540',
    'cat_name' => 'IBM',
    'measure_unit' => '',
    'parent_id' => '437',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '540',
    'has_children' => '0',
    'goods_num' => '10',
    'level' => 1,
    'id' => '540',
    'name' => 'IBM',
  ),
  542 => 
  array (
    'cat_id' => '542',
    'cat_name' => 'Fujitsu',
    'measure_unit' => '',
    'parent_id' => '437',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '542',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '542',
    'name' => 'Fujitsu',
  ),
  544 => 
  array (
    'cat_id' => '544',
    'cat_name' => 'MSI',
    'measure_unit' => '',
    'parent_id' => '437',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '544',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '544',
    'name' => 'MSI',
  ),
  438 => 
  array (
    'cat_id' => '438',
    'cat_name' => 'Desktop Computers',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '438',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '438',
    'name' => 'Desktop Computers',
  ),
  454 => 
  array (
    'cat_id' => '454',
    'cat_name' => 'Apple',
    'measure_unit' => '',
    'parent_id' => '438',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '454',
    'has_children' => '0',
    'goods_num' => '31',
    'level' => 1,
    'id' => '454',
    'name' => 'Apple',
  ),
  455 => 
  array (
    'cat_id' => '455',
    'cat_name' => 'HP',
    'measure_unit' => '',
    'parent_id' => '438',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '455',
    'has_children' => '0',
    'goods_num' => '35',
    'level' => 1,
    'id' => '455',
    'name' => 'HP',
  ),
  515 => 
  array (
    'cat_id' => '515',
    'cat_name' => 'Sony',
    'measure_unit' => '',
    'parent_id' => '438',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '515',
    'has_children' => '0',
    'goods_num' => '18',
    'level' => 1,
    'id' => '515',
    'name' => 'Sony',
  ),
  456 => 
  array (
    'cat_id' => '456',
    'cat_name' => 'Digital SLRs',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '456',
    'has_children' => '4',
    'goods_num' => 0,
    'level' => 0,
    'id' => '456',
    'name' => 'Digital SLRs',
  ),
  457 => 
  array (
    'cat_id' => '457',
    'cat_name' => 'Canon',
    'measure_unit' => '',
    'parent_id' => '456',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '457',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 1,
    'id' => '457',
    'name' => 'Canon',
  ),
  459 => 
  array (
    'cat_id' => '459',
    'cat_name' => 'Nikon',
    'measure_unit' => '',
    'parent_id' => '456',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '459',
    'has_children' => '0',
    'goods_num' => '15',
    'level' => 1,
    'id' => '459',
    'name' => 'Nikon',
  ),
  460 => 
  array (
    'cat_id' => '460',
    'cat_name' => 'Panasonic',
    'measure_unit' => '',
    'parent_id' => '456',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '460',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '460',
    'name' => 'Panasonic',
  ),
  529 => 
  array (
    'cat_id' => '529',
    'cat_name' => 'Leica',
    'measure_unit' => '',
    'parent_id' => '456',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '529',
    'has_children' => '0',
    'goods_num' => '4',
    'level' => 1,
    'id' => '529',
    'name' => 'Leica',
  ),
  464 => 
  array (
    'cat_id' => '464',
    'cat_name' => 'Camcorders',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '464',
    'has_children' => '5',
    'goods_num' => 0,
    'level' => 0,
    'id' => '464',
    'name' => 'Camcorders',
  ),
  466 => 
  array (
    'cat_id' => '466',
    'cat_name' => 'Canon',
    'measure_unit' => '',
    'parent_id' => '464',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '466',
    'has_children' => '0',
    'goods_num' => '24',
    'level' => 1,
    'id' => '466',
    'name' => 'Canon',
  ),
  467 => 
  array (
    'cat_id' => '467',
    'cat_name' => 'JVC',
    'measure_unit' => '',
    'parent_id' => '464',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '467',
    'has_children' => '0',
    'goods_num' => '14',
    'level' => 1,
    'id' => '467',
    'name' => 'JVC',
  ),
  468 => 
  array (
    'cat_id' => '468',
    'cat_name' => 'Samsung',
    'measure_unit' => '',
    'parent_id' => '464',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '468',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 1,
    'id' => '468',
    'name' => 'Samsung',
  ),
  469 => 
  array (
    'cat_id' => '469',
    'cat_name' => 'Sony',
    'measure_unit' => '',
    'parent_id' => '464',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '469',
    'has_children' => '0',
    'goods_num' => '32',
    'level' => 1,
    'id' => '469',
    'name' => 'Sony',
  ),
  470 => 
  array (
    'cat_id' => '470',
    'cat_name' => 'Panasonic',
    'measure_unit' => '',
    'parent_id' => '464',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '470',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 1,
    'id' => '470',
    'name' => 'Panasonic',
  ),
  471 => 
  array (
    'cat_id' => '471',
    'cat_name' => 'TVs & HDTVs',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '471',
    'has_children' => '8',
    'goods_num' => 0,
    'level' => 0,
    'id' => '471',
    'name' => 'TVs & HDTVs',
  ),
  472 => 
  array (
    'cat_id' => '472',
    'cat_name' => 'Toshiba',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '472',
    'has_children' => '0',
    'goods_num' => '16',
    'level' => 1,
    'id' => '472',
    'name' => 'Toshiba',
  ),
  473 => 
  array (
    'cat_id' => '473',
    'cat_name' => 'Sharp',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '473',
    'has_children' => '0',
    'goods_num' => '41',
    'level' => 1,
    'id' => '473',
    'name' => 'Sharp',
  ),
  474 => 
  array (
    'cat_id' => '474',
    'cat_name' => 'Samsung',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '474',
    'has_children' => '0',
    'goods_num' => '38',
    'level' => 1,
    'id' => '474',
    'name' => 'Samsung',
  ),
  475 => 
  array (
    'cat_id' => '475',
    'cat_name' => 'Philips',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '475',
    'has_children' => '0',
    'goods_num' => '24',
    'level' => 1,
    'id' => '475',
    'name' => 'Philips',
  ),
  512 => 
  array (
    'cat_id' => '512',
    'cat_name' => 'Sony',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '512',
    'has_children' => '0',
    'goods_num' => '20',
    'level' => 1,
    'id' => '512',
    'name' => 'Sony',
  ),
  514 => 
  array (
    'cat_id' => '514',
    'cat_name' => 'Panasonic',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '514',
    'has_children' => '0',
    'goods_num' => '37',
    'level' => 1,
    'id' => '514',
    'name' => 'Panasonic',
  ),
  523 => 
  array (
    'cat_id' => '523',
    'cat_name' => 'LG',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '523',
    'has_children' => '0',
    'goods_num' => '34',
    'level' => 1,
    'id' => '523',
    'name' => 'LG',
  ),
  541 => 
  array (
    'cat_id' => '541',
    'cat_name' => 'Pioneer',
    'measure_unit' => '',
    'parent_id' => '471',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '541',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '541',
    'name' => 'Pioneer',
  ),
  486 => 
  array (
    'cat_id' => '486',
    'cat_name' => 'Games Consoles',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '486',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '486',
    'name' => 'Games Consoles',
  ),
  487 => 
  array (
    'cat_id' => '487',
    'cat_name' => 'PlayStation 3',
    'measure_unit' => '',
    'parent_id' => '486',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '487',
    'has_children' => '0',
    'goods_num' => '3',
    'level' => 1,
    'id' => '487',
    'name' => 'PlayStation 3',
  ),
  489 => 
  array (
    'cat_id' => '489',
    'cat_name' => 'Xbox 360',
    'measure_unit' => '',
    'parent_id' => '486',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '489',
    'has_children' => '0',
    'goods_num' => '1',
    'level' => 1,
    'id' => '489',
    'name' => 'Xbox 360',
  ),
  490 => 
  array (
    'cat_id' => '490',
    'cat_name' => 'Wii',
    'measure_unit' => '',
    'parent_id' => '486',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '490',
    'has_children' => '0',
    'goods_num' => '2',
    'level' => 1,
    'id' => '490',
    'name' => 'Wii',
  ),
  496 => 
  array (
    'cat_id' => '496',
    'cat_name' => 'DJ Equipments',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '496',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '496',
    'name' => 'DJ Equipments',
  ),
  497 => 
  array (
    'cat_id' => '497',
    'cat_name' => 'DJ Equipment',
    'measure_unit' => '',
    'parent_id' => '496',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '497',
    'has_children' => '0',
    'goods_num' => '14',
    'level' => 1,
    'id' => '497',
    'name' => 'DJ Equipment',
  ),
  517 => 
  array (
    'cat_id' => '517',
    'cat_name' => 'Motorcycles',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '517',
    'has_children' => '0',
    'goods_num' => '123',
    'level' => 0,
    'id' => '517',
    'name' => 'Motorcycles',
  ),
  519 => 
  array (
    'cat_id' => '519',
    'cat_name' => 'Lens',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '519',
    'has_children' => '0',
    'goods_num' => '24',
    'level' => 0,
    'id' => '519',
    'name' => 'Lens',
  ),
  521 => 
  array (
    'cat_id' => '521',
    'cat_name' => 'MP3/MP4',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '521',
    'has_children' => '0',
    'goods_num' => '17',
    'level' => 0,
    'id' => '521',
    'name' => 'MP3/MP4',
  ),
  522 => 
  array (
    'cat_id' => '522',
    'cat_name' => 'Others',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '522',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 0,
    'id' => '522',
    'name' => 'Others',
  ),
  524 => 
  array (
    'cat_id' => '524',
    'cat_name' => 'Home Entertainment Systems',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '524',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '524',
    'name' => 'Home Entertainment Systems',
  ),
  543 => 
  array (
    'cat_id' => '543',
    'cat_name' => 'Home Entertainment Systems',
    'measure_unit' => '',
    'parent_id' => '524',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '543',
    'has_children' => '0',
    'goods_num' => '24',
    'level' => 1,
    'id' => '543',
    'name' => 'Home Entertainment Systems',
  ),
  527 => 
  array (
    'cat_id' => '527',
    'cat_name' => 'Projector',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '527',
    'has_children' => '1',
    'goods_num' => 0,
    'level' => 0,
    'id' => '527',
    'name' => 'Projector',
  ),
  528 => 
  array (
    'cat_id' => '528',
    'cat_name' => 'Projector',
    'measure_unit' => '',
    'parent_id' => '527',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '528',
    'has_children' => '0',
    'goods_num' => '30',
    'level' => 1,
    'id' => '528',
    'name' => 'Projector',
  ),
  530 => 
  array (
    'cat_id' => '530',
    'cat_name' => 'DVD & GPS Players',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '530',
    'has_children' => '3',
    'goods_num' => 0,
    'level' => 0,
    'id' => '530',
    'name' => 'DVD & GPS Players',
  ),
  531 => 
  array (
    'cat_id' => '531',
    'cat_name' => 'DVD Players',
    'measure_unit' => '',
    'parent_id' => '530',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '531',
    'has_children' => '0',
    'goods_num' => '23',
    'level' => 1,
    'id' => '531',
    'name' => 'DVD Players',
  ),
  532 => 
  array (
    'cat_id' => '532',
    'cat_name' => 'GPS & Navigation',
    'measure_unit' => '',
    'parent_id' => '530',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '532',
    'has_children' => '0',
    'goods_num' => '13',
    'level' => 1,
    'id' => '532',
    'name' => 'GPS & Navigation',
  ),
  533 => 
  array (
    'cat_id' => '533',
    'cat_name' => 'Blu-ray Disc Players',
    'measure_unit' => '',
    'parent_id' => '530',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '533',
    'has_children' => '0',
    'goods_num' => '23',
    'level' => 1,
    'id' => '533',
    'name' => 'Blu-ray Disc Players',
  ),
  545 => 
  array (
    'cat_id' => '545',
    'cat_name' => 'Apple Ipad',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '1',
    'grade' => '0',
    'sort_order' => '545',
    'has_children' => '0',
    'goods_num' => '6',
    'level' => 0,
    'id' => '545',
    'name' => 'Apple Ipad',
  ),
);
?>