<?php
$data = array (
  'shop_name' => 'Cheap Bags Wholesale Professional ltd.',
  'shop_title' => 'Wholesale Handbags : Wholesale Designer Handbags : Wholesale Purses : Replica handbags - cheapbagswholesale.com',
  'shop_desc' => 'Wholesale Handbags, Wholesale Designer Handbags, Wholesale Purses, Replica handbags, Cheap Replica   Wholesale,Handbags Wholesale From China',
  'shop_keywords' => 'Wholesale Handbags, Wholesale Designer Handbags, Wholesale Purses, Replica handbags, Cheap Replica   Wholesale,Handbags Wholesale From China',
  'shop_country' => '44',
  'shop_province' => '',
  'shop_city' => '',
  'shop_address' => '',
  'qq' => '',
  'ww' => '',
  'skype' => '',
  'ym' => '',
  'msn' => 'support@cheapbagswholesale.com',
  'service_email' => 'support@cheapbagswholesale.com',
  'service_phone' => '',
  'shop_closed' => '0',
  'close_comment' => '',
  'shop_logo' => '',
  'licensed' => '0',
  'user_notice' => 'Welcome to Cheap Bags Wholesale Online Shop.',
  'shop_notice' => 'Welcome to Cheap Bags Wholesale Online Shop. We are leading supplier of Cheap Bags including armani HandBags, bally HandBags, burberry HandBags, chanel HandBags, gucci HandBags and other more. Everyone is entitled to be elegant and enjoy luxurious life. And MoreBags, a famous shop for Cheap Bags, lets all people, enjoy this kind of life by providing cheap Bags wholesale.',
  'shop_reg_closed' => '0',
  'lang' => 'en_us',
  'icp_number' => '',
  'icp_file' => '',
  'watermark' => '',
  'watermark_place' => '0',
  'watermark_alpha' => 65,
  'use_storage' => '0',
  'market_price_rate' => 1.2,
  'rewrite' => '2',
  'integral_name' => 'integral',
  'integral_scale' => 1,
  'integral_percent' => '1',
  'sn_prefix' => 'ECS',
  'comment_check' => '1',
  'no_picture' => 'images/no_picture.gif',
  'stats_code' => '<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push([\'_setAccount\', \'UA-791706-41\']);
  _gaq.push([\'_trackPageview\']);

  (function() {
    var ga = document.createElement(\'script\'); ga.type = \'text/javascript\'; ga.async = true;
    ga.src = (\'https:\' == document.location.protocol ? \'https://ssl\' : \'http://www\') + \'.google-analytics.com/ga.js\';
    var s = document.getElementsByTagName(\'script\')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>',
  'cache_time' => 3600,
  'register_points' => '0',
  'enable_gzip' => '0',
  'top10_time' => 0,
  'timezone' => '8',
  'upload_size_limit' => '64',
  'cron_method' => '0',
  'comment_factor' => '3',
  'enable_order_check' => '1',
  'default_storage' => 9999,
  'bgcolor' => '#FFFFFF',
  'visit_stats' => 'on',
  'send_mail_on' => 'off',
  'auto_generate_gallery' => '1',
  'retain_original_img' => '1',
  'member_email_validate' => '0',
  'message_board' => '0',
  'certificate_id' => '1128385134',
  'token' => 'a544f32047123f4d549ba71e2b2206fbee85da68582a1a58870c4fc4208380a6',
  'certi' => 'http://service.shopex.cn/openapi/api.php',
  'date_format' => 'Y-m-d',
  'time_format' => 'd/m/Y H:i:s',
  'currency_format' => '$%s',
  'thumb_width' => 100,
  'thumb_height' => 100,
  'image_width' => 340,
  'image_height' => 300,
  'top_number' => 10,
  'history_number' => 5,
  'comments_number' => 5,
  'bought_goods' => 3,
  'article_number' => 8,
  'goods_name_length' => 15,
  'price_format' => '5',
  'page_size' => 20,
  'sort_order_type' => '0',
  'sort_order_method' => '0',
  'show_order_type' => '1',
  'attr_related_number' => '5',
  'goods_gallery_number' => 5,
  'article_title_length' => '16',
  'name_of_region_1' => 'Countries',
  'name_of_region_2' => '',
  'name_of_region_3' => '',
  'name_of_region_4' => '',
  'search_keywords' => 'Cheap Bags',
  'related_goods_number' => '4',
  'help_open' => '1',
  'article_page_size' => '10',
  'page_style' => '1',
  'recommend_order' => '1',
  'index_ad' => 'sys',
  'can_invoice' => '0',
  'use_integral' => '0',
  'use_bonus' => '0',
  'use_surplus' => '0',
  'use_how_oos' => '0',
  'send_confirm_email' => '0',
  'send_ship_email' => '0',
  'send_cancel_email' => '0',
  'send_invalid_email' => '0',
  'order_pay_note' => '0',
  'order_unpay_note' => '0',
  'order_ship_note' => '0',
  'order_receive_note' => '0',
  'order_unship_note' => '0',
  'order_return_note' => '0',
  'order_invalid_note' => '0',
  'order_cancel_note' => '0',
  'invoice_content' => '',
  'anonymous_buy' => '0',
  'min_goods_amount' => 0,
  'one_step_buy' => 0,
  'invoice_type' => 
  array (
    'type' => 
    array (
      0 => '1',
      1 => '2',
      2 => '',
    ),
    'rate' => 
    array (
      0 => 1,
      1 => 1.5,
      2 => 0,
    ),
  ),
  'stock_dec_time' => '0',
  'cart_confirm' => '3',
  'send_service_email' => '0',
  'show_goods_in_cart' => '3',
  'show_attr_in_cart' => '1',
  'smtp_host' => 'localhost',
  'smtp_port' => '25',
  'smtp_user' => '',
  'smtp_pass' => '',
  'smtp_mail' => '',
  'mail_charset' => 'UTF8',
  'mail_service' => '0',
  'smtp_ssl' => '0',
  'integrate_code' => 'ecshop',
  'integrate_config' => '',
  'hash_code' => '31693422540744c0a6b6da635b7a5a93',
  'template' => 'EnTemplate',
  'install_date' => '1283007629',
  'ecs_version' => 'v2.7.2',
  'sms_user_name' => '',
  'sms_password' => '',
  'sms_auth_str' => '',
  'sms_domain' => '',
  'sms_count' => '',
  'sms_total_money' => '',
  'sms_balance' => '',
  'sms_last_request' => '',
  'affiliate' => 'a:3:{s:6:"config";a:7:{s:6:"expire";d:24;s:11:"expire_unit";s:4:"hour";s:11:"separate_by";i:1;s:15:"level_point_all";s:2:"5%";s:15:"level_money_all";s:2:"1%";s:18:"level_register_all";i:2;s:17:"level_register_up";i:60;}s:4:"item";a:4:{i:0;a:2:{s:11:"level_point";s:3:"60%";s:11:"level_money";s:3:"60%";}i:1;a:2:{s:11:"level_point";s:3:"30%";s:11:"level_money";s:3:"30%";}i:2;a:2:{s:11:"level_point";s:2:"7%";s:11:"level_money";s:2:"7%";}i:3;a:2:{s:11:"level_point";s:2:"3%";s:11:"level_money";s:2:"3%";}}s:2:"on";i:1;}',
  'captcha' => '12',
  'captcha_width' => '100',
  'captcha_height' => '20',
  'sitemap' => 'Array',
  'points_rule' => '',
  'flash_theme' => 'dynfocus',
  'stylename' => '',
  'show_goodssn' => '0',
  'show_brand' => '1',
  'show_goodsweight' => '0',
  'show_goodsnumber' => '0',
  'show_addtime' => '0',
  'goodsattr_style' => '1',
  'show_marketprice' => '1',
  'sms_shop_mobile' => '',
  'sms_order_placed' => '0',
  'sms_order_payed' => '0',
  'sms_order_shipped' => '0',
  'wap_config' => '0',
  'wap_logo' => '',
  'message_check' => '1',
  'best_number' => 3,
  'new_number' => 3,
  'hot_number' => 3,
  'promote_number' => 3,
);
?>